name: pose_estimation_local
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.26.*
  - scipy=1.15.*
  - matplotlib=3.10.*
  - pillow
  - pyyaml
  - tqdm
  - opencv=4.10.*
  - pytorch=2.1.*
  - torchvision=0.16.*
  - cpuonly
  - pip:
      - kornia==0.8.2
      - kornia_rs==0.1.10
